// Auto-generated by Portfolio Generator SaaS
// Edit this file to customise your portfolio data

export interface NavItem { label: string; targetId: string; }
export interface ExpertiseItem {
  id: string; num: string; name: string; desc: string;
  type: "dna" | "neural" | "mandala" | "network" | "atom" | "spectrum";
}
export interface ProjectItem {
  id: string; num: string; cat: string; flip: boolean;
  titlePrefix: string; titleHighlight: string; titleSuffix?: string;
  img: string; desc: string; tech: string[]; link: string;
}
export interface TrainingItem { title: string; org: string; desc: string; active: boolean; }
export interface HackathonItem { name: string; date: string; desc: string; }
export interface StatItem { n: string; l: string; }
export interface SocialLink { label: string; url: string; isDownload?: boolean; }
export interface CustomSectionItem { id: string; heading: string; subheading?: string; body?: string; icon?: string; url?: string; }
export interface CustomSection { id: string; type: string; title: string; visible: boolean; items: CustomSectionItem[]; }

export const portfolioData = {
  backgroundAnimation: "vortex",
  colorPalette: "neon-lime",
  customAccentColor: "",
  personal: {
  "name": "Chedi Ouerghi",
  "firstName": "CHEDI",
  "lastName": "OUERGHI",
  "logoText": "CO",
  "role": "Full-Stack Developer",
  "availabilityText": "Open to Work",
  "tagline": "Portfolio — 2026 / 2027",
  "education": "Your University",
  "heroDescription": "Crafting intelligent, scalable digital systems.",
  "heroSubTextLine1": "Full-Stack Developer crafting",
  "heroSubTextLine2": "Next/Nest",
  "primaryCtaText": "View Work",
  "secondaryCtaText": "Let's Talk",
  "scrollText": "Scroll",
  "email": "chediouerghi8@gmail.com",
  "photoUrl": "",
  "photoPosition": "right",
  "cvUrl": "https://res.cloudinary.com/dhlnfpfen/raw/upload/v1791311088/portfolio-assets/cv/msjuuhybehwcyqw77q1u"
},

  seo: {
  "title": "Chedi Ouerghi — Full-Stack Developer",
  "description": "Portfolio of Chedi Ouerghi — Full-Stack Developer",
  "ogTitle": "Chedi Ouerghi — Portfolio",
  "ogDescription": "Full-Stack Developer"
},

  navigation: [
    { label: "Expertise", targetId: "tiles" },
    { label: "Work", targetId: "projects" },
    { label: "About", targetId: "about" },
    { label: "Timeline", targetId: "experience" },
    ...[],
    { label: "Contact", targetId: "contact" },
  ] as NavItem[],

  marquee: ["React","VueJs","Nest","Python","React","VueJs","Nest","Python"],

  expertiseHeader: {
  "titleMain": "Core",
  "titleAccent": "Expertise",
  "badge": "1 Domains"
},

  expertise: [
  {
    "id": "tile-1791311145675",
    "num": "01",
    "desc": "",
    "name": "React/next.js",
    "type": "network"
  }
] as ExpertiseItem[],

  projectsHeader: {
  "titleMain": "Deployed",
  "titleAccent": "Systems"
},

  projects: [
  {
    "id": "pc-1791311182281",
    "num": "01 / 01",
    "cat": "Mental Health care ",
    "flip": false,
    "titlePrefix": "VitaMind",
    "titleHighlight": "VitaMind",
    "titleSuffix": "",
    "img": "https://res.cloudinary.com/dhlnfpfen/image/upload/v1791311343/portfolio-assets/project-pc-1791311182281/zgnpycnwh5vq1btvz6uj.jpg",
    "desc": "VitaMind is an AI-powered mental health support platform for people living with ADHD, bipolar disorder and psychosis, and the clinicians who support them. It bridges everyday life and clinical care through continuous, personalised monitoring and support.\n\n",
    "tech": [],
    "link": "https://www.vitamindspace.com/"
  }
] as ProjectItem[],

  about: {
    ...{
  "statementLine1": "Building the",
  "statementHighlight": "intelligent",
  "statementLine2": "web, one",
  "statementLine3": "system at a time.",
  "paragraphs": []
},
    stats: [
  {
    "n": "5+",
    "l": "Projects"
  }
] as StatItem[],
  },

  timeline: {
    ...{
  "titleMain": "Track",
  "titleAccent": "Record",
  "trainingColumnTitle": "Training & Certifications",
  "hackathonsColumnTitle": "Hackathons"
},
    training: [
  {
    "org": "GomyCode 2022-2023",
    "desc": "",
    "title": "Full-Stack JS",
    "active": true
  }
] as TrainingItem[],
    hackathons: [
  {
    "date": "aug 2026",
    "desc": "",
    "name": "Automate or Die"
  }
] as HackathonItem[],
  },

  contact: {
    ...{
  "label": "— Get in touch",
  "headingLine1": "Let's",
  "headingHighlight": "Build",
  "headingLine2": "Together",
  "email": "chediouerghi8@gmail.com",
  "emailSubject": "Let's connect"
},
    socials: [] as SocialLink[],
  },

  footer: {
  "author": "Chedi Ouerghi",
  "logo": "CO.",
  "credit": "Designed & Built by Chedi Ouerghi"
},

  customSections: [] as CustomSection[],
};
